### ISSUE TITLE
Setting checkbox state at page load

### ISSUE THREAD

**Issue by nseidle** [mobizt/ESPForm#1]
Great library! Do you have an example that shows how to set the checkbox state at page load? The WiFiSettings example comes close but uses the [loadElementConfig()](https://github.com/mobizt/ESPForm/blob/master/examples/WiFiSettings/WiFiSettings.ino#L185) whereas I'm trying to set the element via `setElementContent()`.

**Comment by nseidle** [comment]
I ended up using runscript to activate a JS .check routine. Is there a better way?

    //Use JS to activate a radio button or check box
    void setElementContent(const char* id, bool settingValue)
    {
      char temp[100];

      if (settingValue == true)
        sprintf(temp, "check('%s', true);", id);
      else
        sprintf(temp, "check('%s', false);", id);
      ESPForm.runScript(temp);
    }

and 

    function check(id, state) {
        ge(id).checked = state;
    }

**Comment by mobizt** [comment]
If that checkbox was already created in the html document not later adding by DOM or javascript, you can use onload event of body like this https://www.w3schools.com/jsref/event_onload.asp
