### ISSUE TITLE
hwcrypto/sha not found

### ISSUE THREAD

**Issue by logowe** [mobizt/ESPForm#3]
Hello I get a compiler error. It doesn't find a library referenced by your own library.
This may be caused by mewer versions of SW I use. After searching araound a while I decided to kindly ask you, knowing your stuff best!

Arduino IDE 2.0.0r7 (less relevant, I suppose)
Espressif Board Manager 2.0.3

Do you have a suggestion?

Here is the compiler output:
===============================
....
Alternatives for hwcrypto/sha.h: []
ResolveLibrary(hwcrypto/sha.h)
  -> candidates: []
d:\ESP_Projekte\ESP32\libraries\ESPForm-master\src\WebSockets\WebSockets.cpp:42:10: fatal error: hwcrypto/sha.h: No such file or directory
 #include <hwcrypto/sha.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
....
================================================

Thanks

**Comment by mobizt** [comment]
This is not the cause of error as this file is not included in esp32 sdk v2.03 and with the compiler guard which this include line should not compile.
You should post all errors instead of last error.

**Comment by mobizt** [comment]
Ok I found the issue because of outdated ArduinoWebsocket library.

You should download [these files](https://github.com/Links2004/arduinoWebSockets/tree/master/src) and replace the old files [here](https://github.com/mobizt/ESPForm/tree/master/src/WebSockets).

**Comment by logowe** [comment]
Hello mobitzt
A better late then never feedback: 
I gave it a try again and it works now. I suppose probably due to several updates since June.
